#pragma once

#ifndef _CHANNELTYPE_H_
#define _CHANNELTYPE_H_ 

// action and reaction command
enum ChannelTypeEnum {
	// action
	CHANNELTYPE_MAP		= 0,		// map channel
	CHANNELTYPE_PARTY,				// party channel
	CHANNELTYPE_GANG,
	CHANNELTYPE_GUILD,				// guild channel
	CHANNELTYPE_PRIVATE,
	CHANNELTYPE_GLOBAL,				// global channel for player chatting
	CHANNELTYPE_COUPLE,				// couple channel
	CHANNELTYPE_SYSTEM,
	CHANNELTYPE_RUMOR,
	CHANNELTYPE_OFFICIAL,			//official channel for horse light or system
	CHANNELTYPE_CHATROOM,
	CHANNELTYPE_NOTICE,
	CHANNELTYPE_SPEAKER,
	CHANNELTYPE_FRIEND,				// Friend channel 
	CHANNELTYPE_INSTANCE,			//villa task ectype
	
	MAX_CHANNELTYPE,				
};

enum MsgReturnEnum {
	// action
	MSG_RETURN_SUCCESS		= 0,		// normal channel
	MSG_RETURN_FAIL,
	MSG_RETURN_FAIL_TOO_FREQUENT,				// team channel
	MSG_RETURN_FAIL_NOT_FOUND,
	MSG_RETURN_FAIL_NO_RIGHT_NO_COUNT,
	MSG_RETURN_FAIL_NO_RIGHT_LV,
	MSG_RETURN_FAIL_NO_RIGHT_BLOCK,
	MSG_RETURN_FAIL_TOO_LONG,
	MSG_RETURN_FAIL_NO_RIGHT_MONEY,
	MSG_RETURN_SUCCESS_COST_MONEY,
	MSG_RETURN_FAIL_NO_RIGHT_MONEY_GANG,
	MSG_RETURN_SUCCESS_COST_MONEY_GANG,
	MSG_RETURN_FAIL_INACTIVE,
	MSG_RETURN_FAIL_TOO_MUCH,
	MSG_RETURN_FAIL_NO_FRIEND_ONLINE,
	MSG_RETURN_FAIL_NOT_FRIEND,
	MAX_MSG_RETURN,				
};

enum ChannelErr {
	CHANNELERR_NOT_FOUND = 0,
	CHANNELERR_CHANNEL_EXIST,
	CHANNEL_NO_ERR,
};

enum ChanneJoinMode{
	CHANNEL_JOIN_MODE_CREATE_IF_NOT_EXIST = 0,
	CHANNEL_JOIN_MODE_JOIN_ONLY_EXIST,
	CHANNEL_JOIN_MODE_NOT_CREATE_IF_EXIST,
};

const PCSTRING ChannelPrefix[MAX_CHANNELTYPE] = {_T("MAP"), _T("PARTY"), _T("GANG"), _T("GUILD"), _T("PRIVATE"), _T("GLOBAL"), _T("COUPLE"),  _T("SYSTEM"), _T("RUMOR")
, _T("OFFICIAL"), _T("CHATROOM"), _T("NOTICE"), _T("SPEAKER"),_T("FRIEND"),_T("INSTANCE")};
const PCSTRING Del = _T("_");

#endif // _BATTLECODE_H_