#ifndef _EXPORTVERSION_H_
#define _EXPORTVERSION_H_

// last modified update: 01-09-2008 (DD-MM-YYYY)

// For Client
#define EXPORT_DATA_CLIENT_MAP_INFO_FORMAT_VERSION				4
#define EXPORT_DATA_CLIENT_NPC_TEMPLATE_FORMAT_VERSION			6
#define EXPORT_DATA_CLIENT_MOB_TEMPLATE_FORMAT_VERSION			9
#define EXPORT_DATA_CLIENT_MAP_INSTANCE_FORMAT_VERSION			4
#define EXPORT_DATA_CLIENT_MAP_ZONEDATA_FORMAT_VERSION			3
// For both Client/Server
#define EXPORT_DATA_MAP_PATHFIND_FORMAT_VERSION					3
// For Server
#define EXPORT_DATA_SERVER_MAP_INFO_FORMAT_VERSION				4
#define EXPORT_DATA_SERVER_NPC_TEMPLATE_FORMAT_VERSION			5
#define EXPORT_DATA_SERVER_MOB_TEMPLATE_FORMAT_VERSION			7
#define EXPORT_DATA_SERVER_MAP_INSTANCE_FORMAT_VERSION			4
#define EXPORT_DATA_SERVER_MAP_ZONEDATA_FORMAT_VERSION			3

#endif //_EXPORTVERSION_H_
