#pragma once
#ifndef _VERSION_H_
#define _VERSION_H_

#include <Reuben\System\Version.h>

//-- Version

#define VERSION_MAJOR		0
#define VERSION_MINOR		5
#define VERSION_PUBLISH		0
#define VERSION_REVISION	12548
#define VERSION_BUILD		0

#define VERSION_MAJOR_STRING		RN_MARCO_TO_STRING(VERSION_MAJOR)
#define VERSION_MINOR_STRING		RN_MARCO_TO_STRING(VERSION_MINOR)
#define VERSION_PUBLISH_STRING		RN_MARCO_TO_STRING(VERSION_PUBLISH)
#define VERSION_REVISION_STRING		RN_MARCO_TO_STRING(VERSION_REVISION)
#define VERSION_BUILD_STRING		RN_MARCO_TO_STRING(VERSION_BUILD)

#define VERSION_NUMBER		RN_VERSION_TO_NUMBER(VERSION_MAJOR, VERSION_MINOR, VERSION_PUBLISH, VERSION_REVISION)
#define VERSION_STRING		RN_VERSION_TO_STRING(VERSION_MAJOR, VERSION_MINOR, VERSION_PUBLISH, VERSION_REVISION, VERSION_BUILD)

#endif // _VERSION_H_
